---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.115.194
      ansible_connection: ssh
      ansible_user: yaha
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
vector:
  hosts:
    clickhouse-02:
      ansible_host: 158.160.103.51
      ansible_connection: ssh
      ansible_user: yaha
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
lighthouse:
  hosts:
    clickhouse-03:
      ansible_host: 158.160.124.60
      ansible_connection: ssh
      ansible_user: yaha
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub